"""Brewfile formatting with Anthropic API integration.

This module handles formatting Brewfiles using the Anthropic API to add
descriptions, categorization, and documentation.
"""

import anthropic


class BrewfileFormatterError(Exception):
    """Exception raised for Brewfile formatting errors."""

    pass


def build_formatting_prompt(raw_content: str) -> str:
    """Build the prompt for Anthropic API to format a Brewfile.

    Args:
        raw_content: The raw Brewfile content from brew bundle dump.

    Returns:
        The formatted prompt string for the Anthropic API.
    """
    return f"""Format the following Brewfile with these requirements:

1. Add a header at the top noting this file was generated by `den`
2. Add a one-liner description comment above each package explaining what it does
3. Organize packages into logical categories with section headers (e.g., "# Development Tools", "# Productivity", "# Media", etc.)
4. Preserve all original package entries - do not remove or modify any packages
5. Use Ruby comment syntax (# for comments)

Return ONLY the formatted Brewfile content, no explanations or markdown code blocks.

Raw Brewfile:
{raw_content}"""


def format_brewfile(raw_content: str, api_key: str) -> str:
    """Send Brewfile to Anthropic for formatting with descriptions.

    Args:
        raw_content: The raw Brewfile content from brew bundle dump.
        api_key: Anthropic API key for authentication.

    Returns:
        The formatted Brewfile content with descriptions and categories.

    Raises:
        BrewfileFormatterError: If the API call fails.
    """
    prompt = build_formatting_prompt(raw_content)

    try:
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}],
        )
        # Extract text content from the response
        if message.content and len(message.content) > 0:
            return message.content[0].text
        raise BrewfileFormatterError("Empty response from Anthropic API")
    except anthropic.APIConnectionError as e:
        raise BrewfileFormatterError(f"Failed to connect to Anthropic API: {e}") from e
    except anthropic.RateLimitError as e:
        raise BrewfileFormatterError(f"Anthropic API rate limit exceeded: {e}") from e
    except anthropic.APIStatusError as e:
        raise BrewfileFormatterError(
            f"Anthropic API error: {e.status_code} - {e.message}"
        ) from e
